# Redis-lite Configuration File

# The port the server listens on
port=6379

# Set to greater than 0 to act as a Follower (Replica)
leader_port=0

# Maximum number of keys to hold in RAM before LRU eviction triggers
max_memory=5

# The name of the Append-Only File on disk
aof_file=database.aof